"""Initial migration with category soft delete

Revision ID: 6aedf83a4f4e
Revises: 
Create Date: 2026-03-20 15:28:35.266745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6aedf83a4f4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), nullable=True))

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
